export const labels = {
    surname: {
        ast: 'apellíu',
        bar: 'Schreibnam',
        br: 'anv-tiegezh',
        ca: 'cognom',
        cs: 'příjmení',
        da: 'efternavn',
        de: 'Familienname',
        'de-at': 'Familienname',
        'de-ch': 'Familienname',
        en: 'family name',
        'en-ca': 'family name',
        'en-gb': 'surname',
        eo: 'familia nomo',
        es: 'apellido',
        et: 'perekonnanimi',
        eu: 'abizen',
        fi: 'sukunimi',
        fit: 'sukunimi',
        fo: 'ættarnavn',
        fr: 'nom de famille',
        ga: 'sloinne',
        gl: 'apelido',
        hr: 'prezime',
        is: 'eftirnafn',
        it: 'cognome',
        la: 'nomen gentilicium',
        lt: 'pavardė',
        lv: 'uzvārds',
        mi: 'ingoa whānau',
        nl: 'achternaam',
        oc: 'nom d\'ostal',
        pl: 'nazwisko',
        pms: 'cognòm',
        pt: 'sobrenome',
        'pt-br': 'nome de família',
        ro: 'nume de familie',
        sco: 'faimily name',
        sk: 'priezvisko',
        sl: 'priimek',
        sq: 'mbiemër',
        sv: 'efternamn',
        tr: 'soyadı',
        wa: 'no d\'famile',
        zu: 'isibongo',
      }
  };