import { WikidataSurnamesRecycler } from './libs/wikidata-surnames-recycler.mjs';
import { Surname } from './libs/surname-creator.mjs';

surnameRecycle([
  //surnames
 //"Antonica","Aphel","Arruga","Artesi","Nuvoletta","Ascagni","Atalmi","Athayde","Auberge","Axat","Babbi","Baccaglio", "Bagnis","Bajlo","Balabio","Balato","Balerdi","Bancalari","Banovac","Barosso","Barzi","Bazzoffia","Beater","Belošević","Bergoli","Bertolla","Berzi","Biasin","Bicini","Bigola","Bioni","Bizarri","Bizzio","Bocșan", "Bogardo","Bojničić","Bolão","Boltri","Boltro","Bonetta","Bordad","Boroni","Bosret","Bossoli","Bostal","Bouzou","Bovara","Mantellini","Maråker","Marcatili","Marcote","Marmone","Marmorosch","Marnet","Marocchino","Marozzo","Marselli","Marsiano","Martay","Martiniani","Mattè","Meani","Meccoli","Megali","Melón","Messea","Mifano","Mignolo","Milita","Millesi","Mitraj","Mobili","Mohorović","Monachesi","Moneti","Monticolo","Monzoni","Morfeo","Mourant","Muelas","Muñagorri","Murato", "Murmura","Muslera","Mutasi","Naria","Navoni","Nedev","Neguț","Nespolino","Nevi","Ninfo","Notarbartolo","Novati",


 // "Boyero","Braghetta","Braides","Bratza","Breganze","Brigidini","Brilli","Brio","Brisca","Broband","Brondi","Brumati","Buffetti","Buhe","Bulbi","Bulgaro","Buonavoglia","Buondelmonti","Burq","Buschiazzo","Buvoli","Cachaça","Cades","Cadi","Cafini","Calabi","Calcagnini","Caldogno","Caldora","Calipari","Caloi","Calzini","Camassa","Cammeo","Campanacci","Campovecchio","Camuzzi","Canalis","Canazei","Cantile","Cantisani","Capato","Capè","Capellina","Capellino","Capezzone","Cappi","Caramel","Caravani","Cardu","Carneo","Carpella","Carraretto","Carretti","Carulla","Cascón","Casè","Casirago","Cassandro","Cassioli","Castruccio","Cataletto","Cauz","Cedrola","Cefaly","Celozzi","Cembali","Censore","Cerpi","Cesariano","Charme","Chepman","Chiamparino","Chigi","Chiosa","Ciavarro","Ciccioli","Cicciù","Cignani","Cillero","Cimbrico","Ciocoiu","Cioppi","Ciotto","Citelli","Citi","Colaci","Colombara","Coltellacci",
// "Coltrino","Commodi","Compri","Comps","Conati","Concublet","Conga","Congia","Conseglio","Consolati","Contestabili","Conton","Contte","Convents","Copula","Corà","Coret","Corevi","Cornelli","Corneo","Cornock","Corollario","Coronaro","Corretto","Creti","Crocicchi","Crolla","Cuonz","Cupia","Curlo","Cuttin","Daal","Danelo","Daolio","Datome","Dattila","De Arriba","De Bellis","De Campo","De Julio","De Lagonissa","De Ocampo","De Tilla","Deciani","Degeri","Del Balzo","Del Debbio","Del Drago","Del Junco","Del Pezzo","Della Luna","Deriu","Desiro","Dessy","Dexel","Dinnie","Dobelli","Dobici","Doncel","Donninger","Dornelles","Douhet","Dragón","Duilio","Dybal","Echandi","Elizeche","Espuelas","Etxabe","Euffreducci","Fabón","Fadda","Fady","Fagotti","Failo","Faliero","Familiar","Fanesi","Farigu","Farnbacher","Fastigi","Fatić","Fattouche","Favoriti","Feccia","Fenini","Ferrater","Fian","Fiani","Fibbia","Filini",
// "Fisogni","Fistola","Flagello","Flèche","Focher","Fóes","Foglietti","Foglino","Folador","Folgori","Fonseka","Fontaneto","Förg","Forleo","Forlivesi","Fortebracci","Fortebraccio","Fragata","Franjić","Frasnelli","Frejo","Fretes","Frigoli","Frittella","Frullani","Fuero","Fume","Furiga","Gabbianelli","Gabion","Gaiani","Gaitas","Galaverna","Galesi","Galliussi","Galosi","Garagna","Garagnani","Garattoni","Gattorno","Gemmellaro","Genocchi","Genora","Gerosolimitano","Ghetti","Ghiaccio","Ghinea","Gigena","Gilardini","Giobellina","Giocondi","Giolfino","Gioppi","Giovio","Giubbi","Gloder","Gonzato","Gorreri","Goti","Govar","Governi","Graanoogst","Granderath",
// "Grangeon","Grasmann","Groppo","Guandalini","Guarano","Guidati","Guindani","Gullaci","Guttero","Guzzini","Hadžiosmanović","Haïk","Hajjo","Halty","Hawit","Hendl","Hercolani","Hesina","Heude","Hogenberg","Hollestelle","Hümpel","Hurricane","Hüsgen","Idonea","Ihlebæk","Imbens","Indrio","Infimo","Insola","Invidia","Irredento","Irusta","Isimbardi","Jaja","Jatón","Ježina","Jöback","Joderi","Kambona","Katalinić","Kepi","Kiß","Klabin","Kläner","Knappmann","Kortholt","Krajcar","Kunchev","Kux","Labandeira","Lacana","Lancieri","Langendorff","Lanzerotti","Lapasta","Lapola","Lardo","Lascorz","Lazzi","Lecumberry","Legi","Lercaro","Lerho","Libric","LiPetri","Lissoni","Locardi","Lodigiano","Lomellini","Loterio","Lupot","Luvino","Luxoro","Luzzago","Maccagno","Macchitella","Macor","Maffè","Maggiori","Mähr","Maimeri","Mainero","Malgara","Mallardo","Maloča","Malossi","Mammì","Man","Manazza","Manici",
//Q86009076 Mrkić
//Q65446684 Mzembi
//Noguero (Q48981697)
//Nunziante (Q65076052)
// Oppes (Q65056546)
"Obedeanu","Ocera","Ongania","Onsi","Ortore","Ossari","Pacenza","Paghera","Pagnossin","Pagoto","Palabay","Paluselli","Panagini","Pancaldo","Pancotto","Panitteri","Pannaci","Paramatti","Parani","Parmigiano","Paroni","Pasabi","Pasarin","Paschini","Pasquina",
"Patarra","Pautasso","Paveley","Pays","Pazó","Pediconi","Pelado","Pepio","Pergamini","Pericolo","Persoone","Pertusati","Peschken","Pescucci","Pezzulli","Picozza","Pigini","Pignatta","Pilaš","Pinca","Piossek","Piquè","Pistacchi","Planat","Plestan","Plumari","Plutino","Polverino","Porfida","Potena","Pozzetto","Presca","Presel","Pressling","Prezzi","Pribadi","Priori","Progna","Providenti","Puelma","Puja","Puligo","Puratić","Pustai","Putti","Questi",
"Raddad","Ragione","Râmbu","Rancez","Rapi","Ravaglioli","Raynier","Razionale","Rechtern","Recondo","Recuperati","Regosa","Relitti","Relvas","Remonti","Renoldi","Renonciat","Requeni","Retamales","Ricamo","Ricciolino","Rimessi","Ringwall","Rizotto","Robbes","Rolandi","Rollero","Royuela","Rustico","Salarza","Salatini","Salegi","Salmaso","Salteri","Salutati","Samele","Sampaolesi","Sampaolo","Sanità","Sannio","Sanquirico","Sanvito","Sarasso","Scanavino",
"Scarabello","Scarascia-Mugnozza","Scatolone","Scazzola","Schatzki","Schittulli","Schlegelberger","Schmorl","Sclavi","Scontrino","Seiferheld","Seletti","Senin","Serao","Sertić","Servetto","Shllaku","Sicuri","Siliceo","Silighini","Simonazzi","Siotto","Sirigo","Sizzi","Sleter","Smaila","Șofron","Soldera","Soloa","Sommervogel","Sonar","Soravia","Sosso","Sotgiu","Sowunmi","Spaccamela","Spadi","Spagnulo","Spana","Spandri","Spanne","Spazzo","Specia","Spighi",
"Spinetto","Spirogi","Spisanelli","Spork","Springorum","Spuri","Stambolić","Stame","Stanchi","Statella","Stecco","Stipica","Stivaletti","Strafella","Strinić","Subilia","Summaria","Supusepa","Szegedy","Taffoni","Talajic","Tañada","Tardia","Tarkhov","Tartarini","Taulier","Telò","Teloni","Tempestivi","Tempia","Teodoli","Teppa","Tettamanti","Theodoli","Ticchi","Tich","Tiñga","Tomacelli","Tonoli","Torboli","Torcia","Toresani","Tornioli","Torresano","Tortù",
"Tourn","Touschek","Trafeli","Tragella","Tranfo","Trasande","Träsch","Trenti","Triga","Trincia","Trioli","Trivini","Trombotto","Trommler","Trompa","Tschapka","Tuane","Tuberoso","Tuccimei","Tudorache","Turiaco","Turolo","Tusso","Ulive","Undritz","Urbanis","Urlić","Urribarri","Uruñuela","Utleg","Vajro","Valdano","Valentinis","Valotti","Varalli","Varviso","Vasini","Vegni","Velini","Veljak","Verhaert","Vernicos","Verso","Vets","Vialardi","Vidiri","Vielmann",
"Villador","Vindver","Vineis","Violati","Vistali","Vrac","Wavelet","Welche","Wijkander","Zafarana","Zanzottera","Zappino","Zermiani","Zickermann","Ziella","Ziersch","Ziewer","Zimolo",
]);

async function surnameRecycle(surnames) {
  for (const surname of surnames) {
    const wsr = new WikidataSurnamesRecycler(surname);
    const existing = await wsr.checkIfSurnameExists();
    if (!existing) {
      const s = new Surname(surname);
      await s.createEntity();
    }
  }
}